### PR TITLE
Sinatra model example

### PR DESCRIPTION
**Pull request by waleo**
Contains details that are not immediately obvious:

1. How to set database.yml for OPENSHIFT
2. How to load & use a model with Sinatra

### CODE REVIEW

**Comment by bparees** [comment]
seems like this is missing url bindings to actually exercise the model?

**Comment by waleo** [comment]
Connection to the DB is established in app.rb lines 11-15.

**Comment by bparees** [comment]
sure, but you're not serving any content of out the DB or loading content into it.  it would be a more interesting example if it did.

**Comment by waleo** [comment]
I have an example of reading data commented on line 27 app.rb.

Next step from that would be to create a sqlite db file, put data in there and read it. Is that what you are looking for?

**Comment by bparees** [comment]
I was thinking you might actually create an object if not present and retrieve it as part of the get on '/', (or provide other paths that create/retrieve objects) but the commented out sample is sufficient I guess.

Could you squash your two commits and i'll merge this?

Thanks!

**Comment by waleo** [comment]
@bparees , the commits have been squashed.

**Comment by bparees** [comment]
@waleo i see 4 commits now?

**Comment by waleo** [comment]
@bparees I noticed that. I am thinking that happened because the squash created a new commit for the pull request. The merge commit was required and I see that's where git re-wrote master.

**Comment by waleo** [comment]
@bparees , can you please merge this? The commit history will be fixed after you merge, and that should not hold up the effort that was put into this.

**Pull request merged**
